### ISSUE TITLE
Beth's code review 🌱

### ISSUE THREAD

**Issue by eliazzo** [fac27/rent-shield#45]
UX: The design is super sleek. If I'm being really pedantic, a larger distance between the text and the bottom of the screen in the footer on the mobile view would be good - it feels like it's being cut off.
I noticed some unknown rules in src/app/globals.css

QA: While I'm here I noticed a couple of unused import statements 
SearchBar.tsx
Property.tsx
Also, you still have a the default file next logo src/app/favicon.ico

**Comment by cameochoquer** [comment]
Thanks Beth!
